# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Lean
    command: |
      curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain leanprover/lean4:nightly-2023-03-09 -y
      echo 'export PATH="$HOME/.elan/bin:$PATH"' >> $HOME/.bashrc
      echo '### You can now close this terminal and use use File/Open folder to open the sample you want to play with.'
vscode:
  extensions:
    - leanprover.lean4